name: manila
display_name: Manila
description: Shared File Systems service
service_type: shared-file-systems
defaults:
  actions:
  - log
  - delete
  checks:
  - status
  - age_gt
  - exempt_names
resources:
  share:
    description: Shared file system shares
    actions:
    - log
    - delete
    checks:
    - status
    - age_gt
    - unused
    - exempt_names
  share_snapshot:
    description: Share snapshots
    actions:
    - log
    - delete
    checks:
    - status
    - age_gt
    - exempt_names
  share_network:
    description: Share networks
    actions:
    - log
    checks:
    - age_gt
    - exempt_names
  share_server:
    description: Share servers
    actions:
    - log
    - delete
    checks:
    - status
    - age_gt
    - exempt_names
